[build]
  publish = "."
  command = ""
  functions = "functions"

[build.environment]
  NETLIFY_USE_YARN = "false"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://*.tiktokcdn.com https://*.tiktokcdn-eu.com https://*.tiktokcdn-us.com https://i.ytimg.com https://via.placeholder.com; script-src 'self' https://cdn.jsdelivr.net https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline'"
